// <auto-generated />
using System;
using LunaLoot.Master.Infrastructure.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LunaLoot.Master.Infrastructure.Persistence.EfCore.Migrations
{
    [DbContext(typeof(LunaLootMasterDbContext))]
    partial class LunaLootMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.AccountAggregateRoot.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountUserRef")
                        .HasColumnType("uuid");

                    b.Property<string>("Addresses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.AccountAggregateRoot.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.AddressAggregateRoot.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2024, 5, 18, 17, 36, 22, 461, DateTimeKind.Utc).AddTicks(9793));

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2024, 5, 18, 17, 36, 22, 462, DateTimeKind.Utc).AddTicks(257));

                    b.HasKey("Id");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.InvoiceAggregateRoot.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("IssuerAddressRef")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssuerTaxAdministration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssuerTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReceiptAddressRef")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptTaxAdministration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParentRef")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentRef1")
                        .HasColumnType("uuid");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentRef1");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Identity.Entities.IdentityLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConsumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityLogins", (string)null);
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Identity.Entities.IdentityUserRole", b =>
                {
                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("0f06a74c-6df2-45c7-8591-0eae25944c98"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdentityUserId", "IdentityRoleId");

                    b.HasIndex("IdentityRoleId");

                    b.ToTable("IdentityUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            IdentityUserId = new Guid("61be0adb-a0fd-4fd0-89d0-63f140c2be09"),
                            IdentityRoleId = new Guid("df93739f-ac5a-403c-8627-14816449cadc"),
                            CreatedAt = new DateTime(2024, 5, 18, 17, 36, 22, 456, DateTimeKind.Utc).AddTicks(5412),
                            Id = new Guid("94d507c9-2333-4e23-8daf-903604d4debd"),
                            UpdatedAt = new DateTime(2024, 5, 18, 17, 36, 22, 456, DateTimeKind.Utc).AddTicks(5412)
                        });
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Identity.IdentityRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IdentityRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df93739f-ac5a-403c-8627-14816449cadc"),
                            CreatedAt = new DateTime(2024, 5, 18, 17, 36, 19, 22, DateTimeKind.Utc).AddTicks(3077),
                            Description = "Administrator user of application",
                            Name = "Administrator",
                            Permissions = -1,
                            UpdatedAt = new DateTime(2024, 5, 18, 17, 36, 19, 22, DateTimeKind.Utc).AddTicks(3078),
                            Weight = 999
                        },
                        new
                        {
                            Id = new Guid("6f56a218-f732-4db4-b733-c768c9b897f3"),
                            CreatedAt = new DateTime(2024, 5, 18, 17, 36, 19, 22, DateTimeKind.Utc).AddTicks(3085),
                            Description = "Tanants of the application",
                            Name = "Tenant",
                            Permissions = 0,
                            UpdatedAt = new DateTime(2024, 5, 18, 17, 36, 19, 22, DateTimeKind.Utc).AddTicks(3085),
                            Weight = 1
                        },
                        new
                        {
                            Id = new Guid("b06725ab-db5e-4d2f-b7bd-4938fa13e582"),
                            CreatedAt = new DateTime(2024, 5, 18, 17, 36, 19, 22, DateTimeKind.Utc).AddTicks(3087),
                            Description = "Anonymous user of application",
                            Name = "anonymous",
                            Permissions = 0,
                            UpdatedAt = new DateTime(2024, 5, 18, 17, 36, 19, 22, DateTimeKind.Utc).AddTicks(3087),
                            Weight = 0
                        });
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Identity.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("IdentityUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("61be0adb-a0fd-4fd0-89d0-63f140c2be09"),
                            CreatedAt = new DateTime(2024, 5, 18, 17, 36, 22, 456, DateTimeKind.Utc).AddTicks(5368),
                            Email = "administrator@master.lunaloot",
                            Password = "$2a$16$FcM8a4tv.I3n6Pi.CSYMUOPS6Z7ViqrsU7m7DqZtAePkjOQohbEZW",
                            PhoneNumber = "12345678910",
                            UpdatedAt = new DateTime(2024, 5, 18, 17, 36, 22, 456, DateTimeKind.Utc).AddTicks(5371)
                        });
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.AccountAggregateRoot.Entities.Subscription", b =>
                {
                    b.HasOne("LunaLoot.Master.Domain.Aggregates.AccountAggregateRoot.Account", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.ProductAggregate.Product", b =>
                {
                    b.HasOne("LunaLoot.Master.Domain.Aggregates.ProductAggregate.Product", "Parent")
                        .WithMany("Variants")
                        .HasForeignKey("ParentRef1")
                        .HasPrincipalKey("ParentRef");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Identity.Entities.IdentityLogin", b =>
                {
                    b.HasOne("LunaLoot.Master.Domain.Identity.IdentityUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Identity.Entities.IdentityUserRole", b =>
                {
                    b.HasOne("LunaLoot.Master.Domain.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("IdentityRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LunaLoot.Master.Domain.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.AccountAggregateRoot.Account", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Aggregates.ProductAggregate.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("LunaLoot.Master.Domain.Identity.IdentityUser", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
